### PR TITLE
More IE Enhancements [WIP]

### PR DESCRIPTION
**Pull request by jmchilton**
Still working on getting an RStudio test environment setup - but I was hoping to squeeze these changes in that I think make the IE core framework better as part of the testing.
- Merged latest dev for galaxyproject/galaxy#229.
- Updated IE context to simplify password handling in rstudio IE - 23459f3
- Create new abstractions for reducing duplication and abstracting out launching docker containers (so we can do cool stuff in the future like launch them remotely). 55e523e, 624d540.

Let me know if you dislike any of these changes or see any problems - they haven't been tested yet but I am building a new VM (using https://github.com/jmchilton/galaxy-rstudio-machine/commit/df8484ef5e0cda734ea69c97dd8a94e5633a06a3) to test these changes.

Ping @bgruening also.

### CODE REVIEW

**Comment by bgruening** [comment]
@jmchilton nice little changes! Thanks! 
Not sure about https://github.com/erasche/galaxy/commit/624d540c04eb69ba0bf4f1879598277dfd69a7b2. I think we need more control of `tmp_dir` from the mako file. If you run Docker containers on a different host than Galaxy is running you need to have `tmp_dir` on a shared filesystem. Usually `tempfile.mkdtemp()` is not on such a filesystem. A separate function in `ie_request` which allows to set `dir=` would solve this I guess.

**Comment by jmchilton** [comment]
I agree that sometimes you would need to customize this directory - but doesn't that logic belong with the framework and not mixed in with how IPython or RStudio environments are being setup? I feel like moving it in this way will allow us to universally configure it more easily.

**Comment by bgruening** [comment]
Yes, it makes sense to handle this inside framework and I like this patch overall. I'm just missing a way to force the creation of `temp_dir` into a shared directory.

**Comment by hexylena** [comment]
@bgruening where/when are you trying to force location of the temp dir? I don't remember needing to do that ever with IPython, definitely seems like a framework detail. The way you phrased that, it sounded like you were already running docker containers on a different host, or ... ?

**Comment by hexylena** [comment]
@jmchilton/@bgruening added you to the collaborators list so when you want things added to my PRs you can just push directly to my branches rather than maintaining multiple forks. :)

**Comment by bgruening** [comment]
@erasche I tried once to get `docker-ipython-notebook` running in VM on one special node in our cluster. During this I needed to share a filesystem between the VM and Galaxy. I never got this running, because of CORS issues, but I will try again soon.

**Comment by hexylena** [comment]
Okay, sounds good. I really want to see docker run on a different host, especially through the galaxy jobs mechanism https://github.com/bgruening/galaxy-ipython/issues/4

**Pull request merged**
