### PR TITLE
Different approach to EDAM Mapping

### PR DESCRIPTION
**Pull request by jmchilton**
This allows superclass relationships to define implicit EDAM formats for child datatypes.

Also adds a script to generate a mapping (current output is https://gist.github.com/jmchilton/73cd540d7a08488843d7).

### CODE REVIEW

**Comment by hexylena** [comment]
Yeah, ok, this makes sense

**Comment by odoppelt** [comment]
small question though, will it be possible to get the edam_format, as we get the file_ext using bioblend 
Today, to get the information on the galaxy tools, we use the show_tool function of the Tools class of bioblend with the io_details at TRUE

**Comment by jmchilton** [comment]
@odoppelt I've added this in https://github.com/erasche/galaxy/pull/6. Should work with requiring changes to bioblend. Inputs described via the tools API will now have a `edam_formats` list and outputs will have a `edam_format`.

I guess there are a lot of places Galaxy extensions are still solely used in the API - so I should probably also add a `/api/datatypes/edam_formats` endpoint to describe the mapping.

**Comment by odoppelt** [comment]
@jmchilton ok and thanks for the new #6 and yes it would be great to add the edam_formats endpoint. I can help you on that part, as soon as I finish with the galaxy datatypes missing from EDAM. 
There should be a few new edam types to add soon.

**Comment by jmchilton** [comment]
@odoppelt Glad to hear it would be useful, I have updated #6 with this functionality.

**Pull request merged**
